### PR TITLE
Update Instabug Listing

### PR DESCRIPTION
**Pull request by azamzamy**
• Update headline
• Update url
• Update content
• Replace Image

### CODE REVIEW

**Comment by azamzamy** [comment]
@cjbarber  Hi Chris, I've updated the Instabug listing to match our new branding. Thanks a lot!

**Comment by davisonio** [comment]
Did you wish to change the UTM source to awesomeandroid as well?

**Comment by azamzamy** [comment]
@davisonio  Thanks for the heads up. Appreciate it! I went ahead and changed it.

**Comment by azamzamy** [comment]
@davisonio Just pinging you in case you've missed this :) Thanks!

**Pull request merged**
