### PR TITLE
Add Redsmin

### PR DESCRIPTION
**Pull request by FGRibreau**
Added Redsmin, a SaaS tool for administrating and monitoring Redis

### CODE REVIEW

**Comment by davisonio** [comment]
Please include improvements/fixes to the repo when adding a product you are affiliated with

**Comment by FGRibreau** [comment]
@davisonio I'm sorry I did not understand you what you meant

**Comment by FGRibreau** [comment]
@davisonio hello, why did you close this? I don't understand why this PR was rejected :s

**Comment by davisonio** [comment]
> @davisonio hello, why did you close this? I don't understand why this PR was rejected :s

Hello, we're looking for other improvements or fixes to this list if you work at the company which the item is being added.

**Pull request closed without merging**
