### PR TITLE
Added Taskade

### PR DESCRIPTION
**Pull request by johnxie**
Please consider adding [Taskade](https://taskade.com) to the list. Thanks!

### CODE REVIEW

**Comment by davisonio** [comment]
> If you are adding a tool you are affiliated with please include other improvements/fixes to the repo.

**Comment by johnxie** [comment]
@davisonio Thanks Craig. I just updated the PR with few additional tools I use.

**Comment by davisonio** [comment]
Added this now thank you

**Comment by johnxie** [comment]
Thank you!

**Pull request merged**
