### PR TITLE
Request to add Userify

### PR DESCRIPTION
**Pull request by jamiesonbecker**
- Userify | https://userify.com | [@userify](https://twitter.com/userify) | free | Securely manage server user accounts, SSH keys, and sudo roles in your cloud or datacenter.

Thanks!

### CODE REVIEW

**Comment by davisonio** [comment]
Hi @jamiesonbecker, could you add a table of contents link to the new section? 😃

**Comment by jamiesonbecker** [comment]
Oh! Yeah sorry :)

**Comment by davisonio** [comment]
Also, could you please include other improvements/fixes to the repo when adding a tool you are affiliated with. There are a few resources further down the list that could do with links, pricing, description etc. Thank you.

**Comment by jamiesonbecker** [comment]
I didn't spot this notification until now, sorry! To clarify: you are looking for some help maintaining the repo, updating info, etc, or userify-specific pricing/links/description etc?

**Comment by davisonio** [comment]
> I didn't spot this notification until now, sorry! To clarify: you are looking for some help maintaining the repo, updating info, etc, or userify-specific pricing/links/description etc?

No problem.

I'm looking for some help maintaining the repo, updating info, etc on resources other than Userify. This is to ensure the longevity of this list.

**Comment by davisonio** [comment]
@jamiesonbecker any update on this?

**Comment by jamiesonbecker** [comment]
Just added Grafana!

**Comment by davisonio** [comment]
> Just added Grafana!

This didn't come through?

Also, I'd prefer if this went under the 'AWS Tools` section instead of creating a new section - otherwise there will be wayyy too many sections! :)

**Comment by jamiesonbecker** [comment]
It was a separate pull request (for Grafana). Userify's not just for AWS btw.. about 40% of our customers are on other clouds or private datacenters.

**Comment by davisonio** [comment]
> It was a separate pull request (for Grafana).

Where?

> Userify's not just for AWS btw.. about 40% of our customers are on other clouds or private datacenters.

But the majority are so I think it would be most appropriate.

**Pull request closed without merging**
