### PR TITLE
added azure boards, pipelines, and repos to the right sections

### PR DESCRIPTION
**Pull request by danhellem**

### CODE REVIEW

**Comment by davisonio** [comment]
> If you are adding a tool you are affiliated with please include other improvements/fixes to the repo.

**Comment by danhellem** [comment]
what other fixes are needed?

**Comment by davisonio** [comment]
Closing - will merge once other improvements are made and merge conflicts are fixed.

**Comment by davisonio** [comment]
Many improvements to be made, add other products, remove dead products, improve descriptions

**Pull request closed without merging**
