### PR TITLE
Identity & Recruiting tools

### PR DESCRIPTION
**Pull request by peytons**
- Resources for Identity Verification & Recruiting
- Moved "Search" category to be adjacent to "Site Search" (unclear how these are different?)

### CODE REVIEW

**Comment by peytons** [comment]
* Resources for Identity Verification & Recruiting
* Moved "Search" category to be adjacent to "Site Search" (unclear how these are different?)

**Comment by davisonio** [comment]
Perhaps you could add 'Recruiting' to the table of contents.

**Comment by davisonio** [comment]
@peytons 👋🏼

Also please fix the merge conflicts :)

**Comment by davisonio** [comment]
Closing due to lack of response

**Pull request closed without merging**
