### PR TITLE
Adding OneNote to Notes

### PR DESCRIPTION
**Pull request by push7joshi**
We should consider adding onenote

### CODE REVIEW

**Comment by davisonio** [comment]
Could you add their Twitter account, pricing and a short description?

https://twitter.com/msonenote

**Comment by push7joshi** [comment]
Sure thing. Added pricing and description.

**Comment by davisonio** [comment]
Thanks, could you also link the twitter username `@msonenote -> [@msonenote](https://twitter.com/msonenote)`.

**Comment by push7joshi** [comment]
Thanks for checking. I have fixed the handle.

**Comment by davisonio** [comment]
Thanks, merged in!

**Pull request merged**
