### PR TITLE
Adding LogDNA

### PR DESCRIPTION
**Pull request by smusali**

### CODE REVIEW

**Comment by davisonio** [comment]
If affiliated, include other changes to this list.

**Comment by smusali** [comment]
@davisonio what do you mean by other changes? There is no other change...

**Comment by davisonio** [comment]
Have a read of our [contributing guidelines](https://github.com/cjbarber/ToolsOfTheTrade/blob/master/contributing.md). We require people to add other tools, make improvements to the current list/descriptions etc. when adding a tool you're affilkaited with.

**Comment by smusali** [comment]
@davisonio, I have just done all - added `SlideShare` which was missing and tweeted :)

**Comment by davisonio** [comment]
Thanks!

**Pull request merged**
